//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowsRotate {
            get {
                object obj = ResourceManager.GetObject("arrowsRotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {&quot;id&quot;:1,&quot;iso&quot;:&quot;AF&quot;,&quot;name&quot;:&quot;AFGHANISTAN&quot;,&quot;nicename&quot;:&quot;Afghanistan&quot;,&quot;iso3&quot;:&quot;AFG&quot;,&quot;numcode&quot;:4,&quot;phonecode&quot;:93},
        ///  {&quot;id&quot;:2,&quot;iso&quot;:&quot;AL&quot;,&quot;name&quot;:&quot;ALBANIA&quot;,&quot;nicename&quot;:&quot;Albania&quot;,&quot;iso3&quot;:&quot;ALB&quot;,&quot;numcode&quot;:8,&quot;phonecode&quot;:355},
        ///  {&quot;id&quot;:3,&quot;iso&quot;:&quot;DZ&quot;,&quot;name&quot;:&quot;ALGERIA&quot;,&quot;nicename&quot;:&quot;Algeria&quot;,&quot;iso3&quot;:&quot;DZA&quot;,&quot;numcode&quot;:12,&quot;phonecode&quot;:213},
        ///  {&quot;id&quot;:4,&quot;iso&quot;:&quot;AS&quot;,&quot;name&quot;:&quot;AMERICAN SAMOA&quot;,&quot;nicename&quot;:&quot;American Samoa&quot;,&quot;iso3&quot;:&quot;ASM&quot;,&quot;numcode&quot;:16,&quot;phonecode&quot;:1684},
        ///  {&quot;id&quot;:5,&quot;iso&quot;:&quot;AD&quot;,&quot;name&quot;:&quot;ANDORRA&quot;,&quot;nicename&quot;:&quot;Andorra&quot;,&quot;iso3&quot;:&....
        /// </summary>
        internal static string countryCodes {
            get {
                return ResourceManager.GetString("countryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {&quot;id&quot;:1,&quot;mission_name&quot;:&quot;Road Rage&quot;,&quot;mission_file&quot;:&quot;DMK_01A.BMS&quot;,&quot;game&quot;:0,&quot;gametype&quot;:&quot;DM&quot;},
        ///  {&quot;id&quot;:2,&quot;mission_name&quot;:&quot;City Madness&quot;,&quot;mission_file&quot;:&quot;DMM_01A.BMS&quot;,&quot;game&quot;:0,&quot;gametype&quot;:&quot;DM&quot;},
        ///  {&quot;id&quot;:3,&quot;mission_name&quot;:&quot;Cracked&quot;,&quot;mission_file&quot;:&quot;DMM_01E.BMS&quot;,&quot;game&quot;:0,&quot;gametype&quot;:&quot;DM&quot;},
        ///  {&quot;id&quot;:4,&quot;mission_name&quot;:&quot;Walled In&quot;,&quot;mission_file&quot;:&quot;DMM_01G.BMS&quot;,&quot;game&quot;:0,&quot;gametype&quot;:&quot;DM&quot;},
        ///  {&quot;id&quot;:5,&quot;mission_name&quot;:&quot;Mines Eye&quot;,&quot;mission_file&quot;:&quot;DMM_01H.BMS&quot;,&quot;game&quot;:0,&quot;gametype&quot;:&quot;DM&quot;},
        ///  {&quot;id&quot;:6,&quot;mission_name&quot;:&quot;Stadium Riot&quot;,&quot;mis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultMaps {
            get {
                return ResourceManager.GetString("defaultMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser {
            get {
                object obj = ResourceManager.GetObject("eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folderMinus {
            get {
                object obj = ResourceManager.GetObject("folderMinus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folderOpen {
            get {
                object obj = ResourceManager.GetObject("folderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folderPlus {
            get {
                object obj = ResourceManager.GetObject("folderPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hosting {
            get {
                object obj = ResourceManager.GetObject("hosting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notactive {
            get {
                object obj = ResourceManager.GetObject("notactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nothosting {
            get {
                object obj = ResourceManager.GetObject("nothosting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap playerTileBlack {
            get {
                object obj = ResourceManager.GetObject("playerTileBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap playerTileBlue {
            get {
                object obj = ResourceManager.GetObject("playerTileBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap playerTileRed {
            get {
                object obj = ResourceManager.GetObject("playerTileRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scoring {
            get {
                object obj = ResourceManager.GetObject("scoring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload {
            get {
                object obj = ResourceManager.GetObject("upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
